[settings]
experimental = true
python.uv_venv_auto = true
status.show_tools = true

[settings.cargo]
binstall = true

[tools]
"cargo:jj-cli" = "latest"
"cargo-binstall" = "latest"
"cargo:starship" = "latest"
